global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:

rule_files:

scrape_configs:
- job_name: 'elementary_caher'
  static_configs:
  - targets: ['elementary_cacher:9071']

alerting:
remote_write:
remote_read: